server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dev-sphere
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect